---
javascripts:
- base:
  - jquery
  - rails
  - highlight.pack
  - application
- panel:
  - jquery.markitup.pack
  - markitup.set
stylesheets:
- ie:
  - ie
- screen:
  - screen
- print:
  - print
- panel:
  - panel
  - markdown_style
  - markitup_style
