name: "Bruno Chagas"
description: "Front-end Engineer"
about: ""

hoptoad: "YOUR KEY HERE"

host: "http://bchagas.com.br"

google_analytics:
  tracker_id: 'Tracker'

get_clicky:
  tracker_id: 'Tracker'

disqus:
  account: 'bchagas'
